
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSOMASUBleftMULnonassocPAPFDIV MUL NUM PA PF SOMA SUBinicio : expressaoexpressao : NUMexpressao : expressao SOMA expressaoexpressao : expressao SUB expressaoexpressao : expressao MUL expressaoexpressao : expressao DIV expressaoexpressao : PA expressao PF'
    
_lr_action_items = {'NUM':([0,4,5,6,7,8,],[3,3,3,3,3,3,]),'PA':([0,4,5,6,7,8,],[4,4,4,4,4,4,]),'$end':([1,2,3,10,11,12,13,14,],[0,-1,-2,-3,-4,-5,-6,-7,]),'SOMA':([2,3,9,10,11,12,13,14,],[5,-2,5,-3,-4,-5,5,-7,]),'SUB':([2,3,9,10,11,12,13,14,],[6,-2,6,-3,-4,-5,6,-7,]),'MUL':([2,3,9,10,11,12,13,14,],[7,-2,7,7,7,-5,7,-7,]),'DIV':([2,3,9,10,11,12,13,14,],[8,-2,8,-3,-4,-5,8,-7,]),'PF':([3,9,10,11,12,13,14,],[-2,14,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'expressao':([0,4,5,6,7,8,],[2,9,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> expressao','inicio',1,'p_inicio','yaccer.py',6),
  ('expressao -> NUM','expressao',1,'p_expressao_numero','yaccer.py',10),
  ('expressao -> expressao SOMA expressao','expressao',3,'p_expressao_soma','yaccer.py',14),
  ('expressao -> expressao SUB expressao','expressao',3,'p_expressao_subtracao','yaccer.py',18),
  ('expressao -> expressao MUL expressao','expressao',3,'p_expressao_multiplicacao','yaccer.py',22),
  ('expressao -> expressao DIV expressao','expressao',3,'p_expressao_divisao','yaccer.py',26),
  ('expressao -> PA expressao PF','expressao',3,'p_expressao_parenteses','yaccer.py',30),
]
